MODE 6
CLS

T%=1
REPEAT
PRINT'"Init tune: ";T%
IF T%=1 THEN OSCLI("LOAD MUSIC1 0E00") ELSE OSCLI("LOAD MUSIC2 0E00")
CALL &0E00
PRINT "Playing... press any key for next tune"
REPEAT
*FX19
CALL &0E03
UNTIL INKEY(0)<>-1
T%=T%+1:IF T%>2 THEN T%=1
UNTIL FALSE
