MODE 6
CLS
*LOAD DRIVER 0E00

T%=1
REPEAT
PRINT'"Init tune: ";T%
IF T%=1 THEN CALL &0E00 ELSE CALL &0E03
PRINT "Playing... press any key for next tune"
REPEAT
*FX19
CALL &0E06
UNTIL INKEY(0)<>-1
T%=T%+1:IF T%>2 THEN T%=1
UNTIL FALSE
